name: ReSharper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: resharper
        uses: Bennet303/resharper-action@master 
        with:
          solution: BinarySearchTree-CI.sln
